/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipRouteImport } from './routes/vip'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as SlotsRouteImport } from './routes/slots'
import { Route as RouletteRouteImport } from './routes/roulette'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as GamesRouteImport } from './routes/games'
import { Route as Dice3dRouteImport } from './routes/dice-3d'
import { Route as CrateRushRouteImport } from './routes/crate-rush'
import { Route as BlackjackRouteImport } from './routes/blackjack'
import { Route as IndexRouteImport } from './routes/index'

const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const SlotsRoute = SlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const RouletteRoute = RouletteRouteImport.update({
  id: '/roulette',
  path: '/roulette',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const Dice3dRoute = Dice3dRouteImport.update({
  id: '/dice-3d',
  path: '/dice-3d',
  getParentRoute: () => rootRouteImport,
} as any)
const CrateRushRoute = CrateRushRouteImport.update({
  id: '/crate-rush',
  path: '/crate-rush',
  getParentRoute: () => rootRouteImport,
} as any)
const BlackjackRoute = BlackjackRouteImport.update({
  id: '/blackjack',
  path: '/blackjack',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blackjack': typeof BlackjackRoute
  '/crate-rush': typeof CrateRushRoute
  '/dice-3d': typeof Dice3dRoute
  '/games': typeof GamesRoute
  '/missions': typeof MissionsRoute
  '/roulette': typeof RouletteRoute
  '/slots': typeof SlotsRoute
  '/tables': typeof TablesRoute
  '/vip': typeof VipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blackjack': typeof BlackjackRoute
  '/crate-rush': typeof CrateRushRoute
  '/dice-3d': typeof Dice3dRoute
  '/games': typeof GamesRoute
  '/missions': typeof MissionsRoute
  '/roulette': typeof RouletteRoute
  '/slots': typeof SlotsRoute
  '/tables': typeof TablesRoute
  '/vip': typeof VipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blackjack': typeof BlackjackRoute
  '/crate-rush': typeof CrateRushRoute
  '/dice-3d': typeof Dice3dRoute
  '/games': typeof GamesRoute
  '/missions': typeof MissionsRoute
  '/roulette': typeof RouletteRoute
  '/slots': typeof SlotsRoute
  '/tables': typeof TablesRoute
  '/vip': typeof VipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blackjack'
    | '/crate-rush'
    | '/dice-3d'
    | '/games'
    | '/missions'
    | '/roulette'
    | '/slots'
    | '/tables'
    | '/vip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blackjack'
    | '/crate-rush'
    | '/dice-3d'
    | '/games'
    | '/missions'
    | '/roulette'
    | '/slots'
    | '/tables'
    | '/vip'
  id:
    | '__root__'
    | '/'
    | '/blackjack'
    | '/crate-rush'
    | '/dice-3d'
    | '/games'
    | '/missions'
    | '/roulette'
    | '/slots'
    | '/tables'
    | '/vip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlackjackRoute: typeof BlackjackRoute
  CrateRushRoute: typeof CrateRushRoute
  Dice3dRoute: typeof Dice3dRoute
  GamesRoute: typeof GamesRoute
  MissionsRoute: typeof MissionsRoute
  RouletteRoute: typeof RouletteRoute
  SlotsRoute: typeof SlotsRoute
  TablesRoute: typeof TablesRoute
  VipRoute: typeof VipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slots': {
      id: '/slots'
      path: '/slots'
      fullPath: '/slots'
      preLoaderRoute: typeof SlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roulette': {
      id: '/roulette'
      path: '/roulette'
      fullPath: '/roulette'
      preLoaderRoute: typeof RouletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dice-3d': {
      id: '/dice-3d'
      path: '/dice-3d'
      fullPath: '/dice-3d'
      preLoaderRoute: typeof Dice3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crate-rush': {
      id: '/crate-rush'
      path: '/crate-rush'
      fullPath: '/crate-rush'
      preLoaderRoute: typeof CrateRushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blackjack': {
      id: '/blackjack'
      path: '/blackjack'
      fullPath: '/blackjack'
      preLoaderRoute: typeof BlackjackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlackjackRoute: BlackjackRoute,
  CrateRushRoute: CrateRushRoute,
  Dice3dRoute: Dice3dRoute,
  GamesRoute: GamesRoute,
  MissionsRoute: MissionsRoute,
  RouletteRoute: RouletteRoute,
  SlotsRoute: SlotsRoute,
  TablesRoute: TablesRoute,
  VipRoute: VipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
